= Tebako sample applications

This repository provides sample applications to demonstrate usage of Tebako.

Right now there is only one sample.

== Sinatra

Running in standalone mode:

[source,sh]
----
$ cd sinatra
$ bundle install
$ bundle exec ruby app.rb
----

This launches a Sinatra server that responds at:

* http://127.0.0.1:4567
* http://127.0.0.1:4567/api


=== Packaging for MacOS

Install Tebako according to the
https://github.com/tamatebako/tebako[Tebako README].

Run this:

[source,sh]
----
tebako press -e app.rb -o sample.tebako -r sinatra
----

[WARNING]
====
Please do not package "in-place" like:

[source,sh]
----
tebako press -e app.rb -o sample.tebako -r ./
----

Tebako includes all files starting from the root folder into package and
packaging "in-place" will force endless recursive inclusion of the package into
itself.
====


=== Packaging for Ubuntu 20, Alpine Linux

Packaging for Ubuntu and Alpine Linux employs https://github.com/tamatebako/tebako-ci-containers[Tebako Docker containers] available through ghrc.io.

There are no prerequisites for using these containers.

Packaging from inside the container:

[source,sh]
----
tebako press -e app.rb -o sinatra.teb -r sinatra -R 3.2.5
----

Packaging from outside the container for Ubuntu:

[source,sh]
----
$ docker run -v $PWD:/mnt/w -t ghcr.io/tamatebako/tebako-ubuntu-20.04:latest \
  tebako press --root=/mnt/w/sinatra --entry-point=app.rb \
  --output=/mnt/w/sinatra-package --Ruby=3.2.5
----

Packaging from outside the container for Alpine:

[source,sh]
----
$ docker run -v $PWD:/mnt/w -t ghcr.io/tamatebako/tebako-alpine-3.17:latest \
  tebako press --root=/mnt/w/sinatra --entry-point=app.rb \
  --output=/mnt/w/sinatra-package --Ruby=3.2.5
----


=== Packaging for glibc-based Linux distributions using the Ubuntu container

This sample shows how to create portable tebako package for GNU Linux
distributions, such as Red Hat Enterprise Linux, CentOS, Fedora, Rocky Linux,
etc.

Packaging from outside the container for Ubuntu:

[source,sh]
----
$ docker run -v $PWD:/mnt/w -t ghcr.io/tamatebako/tebako-ubuntu-20.04:latest \
  tebako press --root=/mnt/w/sinatra --entry-point=app.rb \
  --output=/mnt/w/sinatra-package --Ruby=3.2.5 --patchelf
----

This command:

* mounts current directory to `/mnt/w`
* packages the application in `/mnt/w/sinatra-package`
* applies the experimental `--patchelf` option to make it portable across
different versions of GLIBC.

Please refer to https://github.com/tamatebako/tebako[tebako README] for more
information.

Support for glibc forward portable packages is subject to the following caveats:

* The `--patchelf` option is currently experimental

* The `--patchelf` option is only available for the GNU toolchain, not yet for
clang/llvm.

* The package is built against the installed OpenSSL version on the system (e.g.
1.1.1), which needs to be present at the target system. If the target system has
a different version of OpenSSL, the package will not work.

== License

Copyright Ribose.

Licensed under the 2-clause BSD license.
