= Tebako sample applications

This repository provides sample applications to demonstrate usage of Tebako.

Right now there is only one sample.

This launches a Sinatra server that responds at:

* http://127.0.0.1:4567
* http://127.0.0.1:4567/api

== Packaging for MacOS
== Prequisites

Before using Tebako, please first setup prerequisites as described in tebako README https://github.com/tamatebako/tebako

== Sinatra

Running without Tebako:

[source,sh]
----
$ cd sinatra
$ bundle install
$ bundle exec ruby app.rb
----

Packaging with Tebako:

[source,sh]
----
tebako press -e app.rb -o sample.tebako -r sinatra
----

Note: please do not package "in-place" like
[source,sh]
----
tebako press -e app.rb -o sample.tebako -r ./
----
Tebako includes all files starting from the root folder into package and packaging "in-place" will force endless recursive inclusion of the package into itself.

== Packaging for Ubuntu 20 and Alpine Linux

Packaging for Ubuntu and Alpine Linux employs https://github.com/tamatebako/tebako-ci-containers[Tebako Docker containers] available through ghrc.io.

There are no prerequisites for using these containers.

Packaging is done from inside containers, were the following command is executed:

[source,sh]
----
tebako press -e app.rb -o sinatra.teb -r sinatra -R 3.2.5
----

== Packaging for Gnu Linux distributions using Ubuntu container
This sample shows hoe to create portable tebako package for GNU Linux distributions.

[source,sh]
----
docker run -v $PWD:/mnt/w -t ghcr.io/tamatebako/tebako-ubuntu-20.04:latest \
              tebako press --root=/mnt/w/sinatra --entry-point=app.rb     \
              --output=/mnt/w/sinatra-package --Ruby=3.2.5 --patchelf
----

Container will mount current directory to /mnt/w and package the application in /mnt/w/sinatra-package
Experimental --patchelf option is used to fix ELF headers in the package to make it portable across different versions of GLIBC.
Please refer to https://github.com/tamatebako/tebako[tebako README] for more information.

Please note that there is one caveat with this approach. The package will be built against OpenSSL 1.1.1 that needs to be installed at the target system.
If the target system has different version of OpenSSL, the package will not work.
