name: Docker

on:
  push:
    branches:  [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - 'ubuntu-20.04'
          - 'alpine-3.17'
        package_ruby_ver:
          - '3.2.5'
          - '3.3.4'
    container:
      image: ghcr.io/tamatebako/tebako-${{ matrix.container }}:latest
    steps:
    - name: Checkout sample
      uses: actions/checkout@v4

    - name: Package
      run: tebako press -e app.rb -o sinatra.teb -r sinatra -R ${{ matrix.package_ruby_ver }}

    - name: Test
      run: ./sinatra.teb -h

    - name: Look around
      run: ls -la

    - name: Start packaged Sinatra application
      run: ./sinatra.teb &
      env:
        PORT: 4567

    - name: Wait for Sinatra to start
      run: sleep 10

    - name: Install curl/procps
      run: |
        if  [ -e "/etc/lsb-release" ]; then
          apt-get -y update
          apt-get -y install curl procps
        elif [ -e "/etc/alpine-release" ]; then
          apk --no-cache --upgrade add curl procps
        fi

    - name: Place GET request
      run: |
        curl http://localhost:4567

    - name: End Sinatra application
      run: pkill -f sinatra.teb
